//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidenciasUdec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.REPORTE = new HashSet<REPORTE>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string TELEFONO { get; set; }
        public string ConfirmarPassword { get; set; }
        public Nullable<int> ID_PROGRAMA { get; set; }
        public string SEMESTRE { get; set; }
        public Nullable<bool> RESTABLECER_PASS { get; set; }
        public Nullable<bool> USER_CONFIRMADO { get; set; }
        public string TOKEN { get; set; }
    
        public virtual PROGRAMA PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE> REPORTE { get; set; }
    }
}
